language: r
cache: packages
warnings_are_errors: false

CODECOV_TOKEN="514c0739-1d67-4167-829f-d038f523544c"

r_packages:
    - dplyr
    - purrr
    - tibble
    - rlang

  
  after_success:
    - Rscript -e ''